apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-kafka-producer
  labels:
    app: fake-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-kafka-producer
  template:
    metadata:
      labels:
        app: fake-kafka-producer
    spec:
      containers:
      - name: fake-kafka-producer
        image: carloshkayser/fake-kafka-producer:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_HOST
          value: "kafka-cluster-kafka-bootstrap:9092"
        - name: KAFKA_TOPIC
          value: "to_predict"
