apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-streaming-app
  namespace: demo
spec:
  imagePullPolicy: Never
  image: carloshkayser/spark-streaming-app:latest
  sparkVersion: "3.2.1"
  mode: cluster
  type: Python
  pythonVersion: "3"
  mainApplicationFile: local:///home/app/app.py
  restartPolicy:
    type: Never

  # volumes:
  #   - name: "test-volume"
  #     hostPath:
  #       path: "/tmp"
  #       type: Directory

  # dynamicAllocation:
  #   enabled: true
  #   initialExecutors: 2
  #   minExecutors: 2
  #   maxExecutors: 10

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.1
    serviceAccount: spark
    # volumeMounts:
    #   - name: "test-volume"
    #     mountPath: "/tmp"

  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.1
    # volumeMounts:
    #   - name: "test-volume"
    #     mountPath: "/tmp"

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fake-kafka-producer
#   labels:
#     app: fake-kafka-producer
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: fake-kafka-producer
#   template:
#     metadata:
#       labels:
#         app: fake-kafka-producer
#     spec:
#       containers:
#       - name: fake-kafka-producer
#         image: carloshkayser/fake-kafka-producer:latest
#         env:
#         - name: APP_NAME
#           value: "Hello from the environment"
#         - name: MASTER
#           value: "k8s://kubernetes.default.svc.cluster.local"
#         imagePullPolicy: Never